### ISSUE TITLE
PCの記事どうしよ

### ISSUE THREAD

**Issue by datt16** [datt16/PC-Phone_Site#51]
## 記事の中身
スペック(基本情報)
- CPU
- GPU
- HDD/SSD
--- 
スペック(載せるか悩んでる)
- イヤホンジャックの有無
- 光学ドライブの有無
- Office関係
- 価格
---
寸法
- 画面サイズ
- 本体サイズ
- 質量

## 記事の量
一応, Teamsにスペックシートは載ってる
![image](https://user-images.githubusercontent.com/44765362/105256000-2bb80880-5bc8-11eb-9ca4-debe68581635.png)
でも、もう時間がないから数を絞りたい

**Comment by makotia** [comment]
> Office関係
どうせ学校でもらえるからいらない気がする

**Comment by datt16** [comment]
> > Office関係
> 
> どうせ学校でもらえるからいらない気がする
> 

それじゃOffice無しで

**Comment by datt16** [comment]
光学ドライブの有無は記載なし
価格は、記事の部分に追記する形でつくれれば良いと思った

**Comment by datt16** [comment]
PC記事仕様

> ・ [項目名] --- [記述例] --- [備考]

### スマホと一緒で大丈夫な部分

- CPU --- intel Core i7 8550U
- RAM --- 8GB
- ストレージ --- SSD: 256GB, HDD: 1TB  
  > カンマ区切りにしてるけどカメラみたいに改行のほうが良いかも
- イヤホンジャック - o/x
- 生体認証
- 寸法
- Markdown部分

### スマホと変える必要がありそうな部分
- バッテリー --- 何を基準に書けば良いか分からん
- カメラ --- 書けん
- 防水・防塵 --- ほとんど対応してない

スマホと変える必要がある部分は基本省略・非表示するように
> 記事生成のプログラムを変更する必要になる可能性があるため
--- 

### todo
- [ ] SpecCardで、値がNULLだったらカードそのものを非表示にするように
- [ ] 記事(Markdown部分)の中身にどんな内容を増やすか決める
- [ ] iPad Pro, XPS13, MacBook Proの記事作成
- [ ] その他PCの記事作成

---
必要に応じ適宜変更予定
